- name: "Create and Delete the file....."
  user: root
  hosts: all
  tasks:
    - name: "Create the file"
      file: path=/tmp/ans-file.txt state=touch

   # - name: "Delete the file"
     # file: path=/opt/tmp/ans-file.txt state=absent

