- name: "install patches"
  user: cwr.vinay.khandalkar
  sudo: yes
  hosts: all
  tasks:
    - name: "upgrade OS"
      yum: 
        update_cache: yes
        name: '*'
        state: latest
   
    - shell: ( sleep 3 && /sbin/reboot & )
      async: 0
      poll: 0
      become: true
      ignore_errors: true
      
    - name: Wait for the server to reboot
      local_action: wait_for host="{{ansible_host}}" delay=15 state=started port="{{ansible_port}}" connect_timeout=10 timeout=180

    - shell: uptime
      
